package llm

import (
	"encoding/json"
	"strings"
)

// Message — unit of communication with LLM (system/user/assistant/tool).
type Message struct {
	Role             string     `json:"role"`                        // "system" | "user" | "assistant" | "tool"
	Content          string     `json:"content"`                     // text content
	ReasoningContent string     `json:"reasoning_content,omitempty"` // chain-of-thought / reasoning content (DeepSeek)
	ToolCalls        []ToolCall `json:"tool_calls,omitempty"`        // tool calls (for assistant)
	ToolCallID       string     `json:"tool_call_id,omitempty"`      // call ID (for tool responses)
	// ReasoningItems carries reasoning output items from the OpenAI Responses API.
	// Each item has an ID (required for round-tripping to the API) and a Summary text.
	// Populated only by the Responses API provider; other providers use ReasoningContent.
	ReasoningItems []ReasoningItem `json:"reasoning_items,omitempty"`
}

// ReasoningItem represents a reasoning output item from the Responses API.
// The ID is required when sending the item back to the API in subsequent requests
// to maintain the reasoning chain across turns.
type ReasoningItem struct {
	ID      string `json:"id"`
	Summary string `json:"summary"`
}

// ToolCall — request to call a tool, generated by LLM.
type ToolCall struct {
	ID    string          `json:"id"`    // unique call ID
	Name  string          `json:"name"`  // tool name
	Input json.RawMessage `json:"input"` // arguments (JSON)
}

// ChatRequest — request to LLM.
type ChatRequest struct {
	Model           string           `json:"model"`
	ModelFamily     string           `json:"model_family,omitempty"` // model family hint (e.g. "anthropic", "deepseek"); auto-detected if empty
	Messages        []Message        `json:"messages"`
	Tools           []ToolDefinition `json:"tools,omitempty"`
	MaxTokens       int              `json:"max_tokens"`
	Temperature     *float64         `json:"temperature,omitempty"`      // nil = use provider default
	ReasoningEffort string           `json:"reasoning_effort,omitempty"` // native reasoning value (e.g. "On", "high", "HIGH")
}

// ChatResponse — LLM response.
type ChatResponse struct {
	Model      string     `json:"model"`  // Model ID used for this response
	Family     string     `json:"family"` // Model family for prompt/parameter adaptation
	Message    Message    `json:"message"`
	Reasoning  string     `json:"reasoning"` // Extended thinking/reasoning (if model supports)
	Usage      TokenUsage `json:"usage"`
	StopReason string     `json:"stop_reason"` // "end_turn" | "tool_use" | "max_tokens"
}

// TokenUsage — token consumption tracking.
type TokenUsage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
}

// normalizeResponse trims trailing whitespace from content and reasoning fields.
func normalizeResponse(resp *ChatResponse) {
	resp.Message.Content = strings.TrimRight(resp.Message.Content, " \t\n\r\f\v")
	resp.Message.ReasoningContent = strings.TrimRight(resp.Message.ReasoningContent, " \t\n\r\f\v")
	resp.Reasoning = strings.TrimRight(resp.Reasoning, " \t\n\r\f\v")
}

// ToolDefinition — tool description for LLM (JSON Schema).
type ToolDefinition struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	InputSchema json.RawMessage `json:"input_schema"`
}
